### ISSUE TITLE
ElasticIP association can fail

### ISSUE THREAD

**Issue by jamescook** [OpenVidu/openvidu-pro-clustering#2]
I received this error launching OpenVidu Pro using the default CF template from the marketplace:

```
You must specify an allocation id when mapping an address to a VPC instance 
(Service: AmazonEC2; Status Code: 400; 
Error Code: InvalidParameterCombination; 
Request ID: de9904e6-850f-477a-b675-6832ae509738)
```
When configured with a VPC, the following resource config fails with the above error in Cloudformation:

```
  MyEIP:
    Type: AWS::EC2::EIPAssociation
    Condition: NoSelfSigned
    Properties:
      InstanceId: !Ref OpenViduServer
      EIP: !Ref PublicElasticIP
```
According to the CF docs, `EIP` is only used for EC2-Classic. For VPC, `AllocationID` must be specified. <sub>[1]</sub>

<sub>[1] https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-eip-association.html</sub>

I worked around the issue by customizing the template to use AllocationID instead of the EIP property.
